### ISSUE TITLE
Solr unrecognized after i run this shell

### ISSUE THREAD

**Issue by jasonhai** [pefferen/vagrant-solr-4.10.2-tomcat7#1]
Hello Pefferen,

Currently i installed solr 4.10.2 by your shell into my vagrant machine on Ubuntu server 14.04.
But after everything run sucessfully with message bellow:

==> default: Configuring Solr
==> default: Set filepermissions
==> default: Setup Tomcat user.
==> default:  \* Stopping Tomcat servlet engine tomcat7
==> default:    ...done.
==> default:  \* Starting Tomcat servlet engine tomcat7
==> default:    ...done.
==> default: Ubuntu, tomcat7 and solr-4.10.4 have been installed.

I vagrant ssh into my machine and run this command 

service solr status
=> It was show this: solr: unrecognized service

Please double checked and lets me know if I wrong somewhere.

I really need this function to create solr server for my project. It would be appreciate if you can take a small  times to verified this. 

Thanks and regards!
          Jason

**Comment by pefferen** [comment]
hi Jason, Solr is not a service. Solr is an application which runs under Tomcat. You could doe `service tomcat7 status` to findout the status of tomcat.

You can reach the instance of solr under the IP adres as set in the _Vagrant_ file. and under port 8080:

```
123.123.123.123:8080/#/solr
```

Hope this helps
